List todayHotChartsData = [
  [
    {'book_name': '倚天屠龙记', 'id': 1},
    {'book_name': '射雕英雄传', 'id': 1},
    {'book_name': '神雕侠侣', 'id': 1},
    {'book_name': '笑傲江湖', 'id': 1},
    {'book_name': '雪山飞狐', 'id': 1},
    {'book_name': '天龙八部', 'id': 1},
    {'book_name': '鹿鼎记', 'id': 1},
    {'book_name': '笑傲江湖', 'id': 1},
    {'book_name': '射雕英雄传', 'id': 1},
    {'book_name': '倚天屠龙记', 'id': 1},
  ],
  [
    {'book_name': '鹿鼎记', 'id': 1},
    {'book_name': '射雕英雄传', 'id': 1},
    {'book_name': '神雕侠侣', 'id': 1},
    {'book_name': '笑傲江湖', 'id': 1},
    {'book_name': '雪山飞狐', 'id': 1},
    {'book_name': '天龙八部', 'id': 1},
    {'book_name': '鹿鼎记', 'id': 1},
    {'book_name': '笑傲江湖', 'id': 1},
    {'book_name': '射雕英雄传', 'id': 1},
    {'book_name': '倚天屠龙记', 'id': 1},
  ],
  [
    {'book_name': '射雕英雄传', 'id': 1},
    {'book_name': '射雕英雄传', 'id': 1},
    {'book_name': '神雕侠侣', 'id': 1},
    {'book_name': '笑傲江湖', 'id': 1},
    {'book_name': '雪山飞狐', 'id': 1},
    {'book_name': '天龙八部', 'id': 1},
    {'book_name': '鹿鼎记', 'id': 1},
    {'book_name': '笑傲江湖', 'id': 1},
    {'book_name': '射雕英雄传', 'id': 1},
    {'book_name': '倚天屠龙记', 'id': 1},
  ],
  [
    {'book_name': '雪山飞狐', 'id': 1},
    {'book_name': '射雕英雄传', 'id': 1},
    {'book_name': '神雕侠侣', 'id': 1},
    {'book_name': '笑傲江湖', 'id': 1},
    {'book_name': '雪山飞狐', 'id': 1},
    {'book_name': '天龙八部', 'id': 1},
    {'book_name': '鹿鼎记', 'id': 1},
    {'book_name': '笑傲江湖', 'id': 1},
    {'book_name': '射雕英雄传', 'id': 1},
    {'book_name': '倚天屠龙记', 'id': 1},
  ],
];